In [0]:
import numpy as np
import pandas as pd
import keras
from google.colab import drive
drive.mount('/content/drive/')
data_path = '/content/drive/My Drive/Colab Notebooks/AML - Assignment 1/'

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
train_data = pd.read_csv(data_path + 'train.csv')
display(train_data)
test_data = pd.read_csv(data_path + 'test.csv')
test_data

LIMIT_BAL  SEX  ...  PAY_AMT6  default.payment.next.month
0        20000.0    2  ...       0.0                           1
1       120000.0    2  ...    2000.0                           1
2        90000.0    2  ...    5000.0                           0
3        50000.0    2  ...    1000.0                           0
4        50000.0    1  ...     679.0                           0
...          ...  ...  ...       ...                         ...
26995    80000.0    1  ...    4000.0                           1
26996   220000.0    1  ...    1000.0                           0
26997   150000.0    1  ...       0.0                           0
26998    30000.0    1  ...    3100.0                           1
26999    80000.0    1  ...    1804.0                           1

[27000 rows x 24 columns]

LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6
0       30000.0    2          3  ...       0.0     379.0       0.0
1      260000.0    2          1  ...     141.0   20074.0   60308.0
2       80000.0    1          1  ...    4000.0    3000.0    5000.0
3       70000.0    2          2  ...    1900.0    1841.0    1945.0
4      400000.0    1          3  ...    4721.0    4114.0    1855.0
...         ...  ...        ...  ...       ...       ...       ...
2995   210000.0    1          1  ...     420.0    1572.0       0.0
2996   360000.0    2          1  ...    8607.0    8843.0    3000.0
2997   110000.0    2          2  ...    2000.0       0.0   93665.0
2998   340000.0    2          1  ...   11372.0    2434.0    2222.0
2999   290000.0    2          1  ...     550.0     550.0       0.0

[3000 rows x 23 columns]

In [0]:
# find missing data
print(np.any(train_data.isnull()))
print(np.any(test_data.isnull()))

False
False


In [0]:
train_targets = train_data['default.payment.next.month'].values
train_data = train_data.iloc[:, :-1]
assert np.all(train_data.columns == test_data.columns), 'Train and test data have different columns and/or a different ordering of them'
train_data

LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6
0        20000.0    2          2  ...       0.0       0.0       0.0
1       120000.0    2          2  ...    1000.0       0.0    2000.0
2        90000.0    2          2  ...    1000.0    1000.0    5000.0
3        50000.0    2          2  ...    1100.0    1069.0    1000.0
4        50000.0    1          2  ...    9000.0     689.0     679.0
...          ...  ...        ...  ...       ...       ...       ...
26995    80000.0    1          2  ...    7000.0       0.0    4000.0
26996   220000.0    1          3  ...    3047.0    5000.0    1000.0
26997   150000.0    1          3  ...     129.0       0.0       0.0
26998    30000.0    1          2  ...    4200.0    2000.0    3100.0
26999    80000.0    1          3  ...    1926.0   52964.0    1804.0

[27000 rows x 23 columns]

In [0]:
print('Train data | n_samples: ', train_data.shape[0])
print('Test data | n_samples: ', test_data.shape[0])
assert np.all(train_data.dtypes == test_data.dtypes), 'The data types of train and test columns do not match'
display(train_data.dtypes)
print('Train targets | n_samples: ', train_targets.size, ' dtype: ', train_targets.dtype)

Train data | n_samples:  27000
Test data | n_samples:  3000


LIMIT_BAL    float64
SEX            int64
EDUCATION      int64
MARRIAGE       int64
AGE            int64
PAY_0          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
dtype: object

Train targets | n_samples:  27000  dtype:  int64


The train and test split of the data is at 90% - 10% ratio. The columns of two datasets have equal names and datatypes, as should be.

## Data Preparation
Let us proceed to normalize the data

In [0]:
display(train_data.describe())
test_data.describe()

LIMIT_BAL           SEX  ...       PAY_AMT5       PAY_AMT6
count    27000.000000  27000.000000  ...   27000.000000   27000.000000
mean    167196.518519      1.603185  ...    4795.497259    5221.980185
std     129337.261882      0.489246  ...   15043.584614   18069.890373
min      10000.000000      1.000000  ...       0.000000       0.000000
25%      50000.000000      1.000000  ...     248.750000     106.750000
50%     140000.000000      2.000000  ...    1504.500000    1500.000000
75%     240000.000000      2.000000  ...    4036.250000    4000.000000
max    1000000.000000      2.000000  ...  426529.000000  528666.000000

[8 rows x 23 columns]

LIMIT_BAL          SEX  ...       PAY_AMT5       PAY_AMT6
count    3000.000000  3000.000000  ...    3000.000000    3000.000000
mean   170074.560000     1.608667  ...    4834.401000    5157.204000
std    133378.599177     0.488130  ...   17250.413316   14891.880054
min     10000.000000     1.000000  ...       0.000000       0.000000
25%     50000.000000     1.000000  ...     279.500000     216.250000
50%    140000.000000     2.000000  ...    1457.000000    1504.500000
75%    240000.000000     2.000000  ...    4020.250000    4416.750000
max    740000.000000     2.000000  ...  388071.000000  220371.000000

[8 rows x 23 columns]

The table above allows us to formulate the following hypotesis
1. no matter what the meaning of the `LIMIT_BAL` variable is, it has a minimum value of 10 000 and a max of 1 000 000.
1. `SEX` is a categorical unordered variable that can only take 1 or 2 as values. We should trasform this variable to a one hot encoding
1. `EDUCATION` can only take integer values between  0 and 6, in all likelyhood corresponding to lower to higher levels of education
1. `MARRIAGE` same as `SEX`, but with four different categories
1. `AGE` is numerical and technically unbunded above, but it can be normalized using as the higher limit the maximum value found in the dataset
1. 

In [0]:
# LIMIT_BAL
min_LIMIT_BAL = 10000
max_LIMIT_BAL = 1000000
train_data['LIMIT_BAL'] = (train_data['LIMIT_BAL'] - min_LIMIT_BAL) / (max_LIMIT_BAL - min_LIMIT_BAL)
train_data['LIMIT_BAL'] = train_data['LIMIT_BAL'].astype('float32')
test_data['LIMIT_BAL'] = (test_data['LIMIT_BAL'] - min_LIMIT_BAL) / (max_LIMIT_BAL - min_LIMIT_BAL)
test_data['LIMIT_BAL'] = test_data['LIMIT_BAL'].astype('float32')
train_data
test_data

LIMIT_BAL  SEX  EDUCATION  ...  PAY_AMT4  PAY_AMT5  PAY_AMT6
0      0.020202    2          3  ...       0.0     379.0       0.0
1      0.252525    2          1  ...     141.0   20074.0   60308.0
2      0.070707    1          1  ...    4000.0    3000.0    5000.0
3      0.060606    2          2  ...    1900.0    1841.0    1945.0
4      0.393939    1          3  ...    4721.0    4114.0    1855.0
...         ...  ...        ...  ...       ...       ...       ...
2995   0.202020    1          1  ...     420.0    1572.0       0.0
2996   0.353535    2          1  ...    8607.0    8843.0    3000.0
2997   0.101010    2          2  ...    2000.0       0.0   93665.0
2998   0.333333    2          1  ...   11372.0    2434.0    2222.0
2999   0.282828    2          1  ...     550.0     550.0       0.0

[3000 rows x 23 columns]

In [0]:
# SEX
# For the sake naming, we will assume that '1' means 'man' and '2' 'woman'
train_sexes = keras.utils.to_categorical(train_data['SEX'])[:, 1:]
train_sexes = pd.DataFrame(train_sexes, columns = ['MALE', 'FEMALE'])
train_sexes
train_data.drop(columns = 'SEX', inplace = True)
train_data = pd.concat((train_data, train_sexes), axis = 'columns')
del train_sexes
train_data

LIMIT_BAL  EDUCATION  MARRIAGE  AGE  ...  PAY_AMT5  PAY_AMT6  MALE  FEMALE
0       0.010101          2         1   24  ...       0.0       0.0   0.0     1.0
1       0.111111          2         2   26  ...       0.0    2000.0   0.0     1.0
2       0.080808          2         2   34  ...    1000.0    5000.0   0.0     1.0
3       0.040404          2         1   37  ...    1069.0    1000.0   0.0     1.0
4       0.040404          2         1   57  ...     689.0     679.0   1.0     0.0
...          ...        ...       ...  ...  ...       ...       ...   ...     ...
26995   0.070707          2         2   34  ...       0.0    4000.0   1.0     0.0
26996   0.212121          3         1   39  ...    5000.0    1000.0   1.0     0.0
26997   0.141414          3         2   43  ...       0.0       0.0   1.0     0.0
26998   0.020202          2         2   37  ...    2000.0    3100.0   1.0     0.0
26999   0.070707          3         1   41  ...   52964.0    1804.0   1.0     0.0

[27000 rows x 24 columns]

In [0]:
# SEX
test_sexes = keras.utils.to_categorical(test_data['SEX'])[:, 1:]
test_sexes = pd.DataFrame(test_sexes, columns = ['MALE', 'FEMALE'])
test_sexes
test_data.drop(columns = 'SEX', inplace = True)
test_data = pd.concat((test_data, test_sexes), axis = 'columns')
del test_sexes
test_data

LIMIT_BAL  EDUCATION  MARRIAGE  AGE  ...  PAY_AMT5  PAY_AMT6  MALE  FEMALE
0      0.020202          3         1   44  ...     379.0       0.0   0.0     1.0
1      0.252525          1         2   28  ...   20074.0   60308.0   0.0     1.0
2      0.070707          1         2   25  ...    3000.0    5000.0   1.0     0.0
3      0.060606          2         2   42  ...    1841.0    1945.0   0.0     1.0
4      0.393939          3         1   33  ...    4114.0    1855.0   1.0     0.0
...         ...        ...       ...  ...  ...       ...       ...   ...     ...
2995   0.202020          1         2   28  ...    1572.0       0.0   1.0     0.0
2996   0.353535          1         1   36  ...    8843.0    3000.0   0.0     1.0
2997   0.101010          2         2   31  ...       0.0   93665.0   0.0     1.0
2998   0.333333          1         2   44  ...    2434.0    2222.0   0.0     1.0
2999   0.282828          1         1   40  ...     550.0       0.0   0.0     1.0

[3000 rows x 24 columns]

In [0]:
# EDUCATION
min_EDU = 0.
max_EDU = 6.
train_data['EDUCATION'] = (train_data['EDUCATION'] - min_EDU) / (max_EDU - min_EDU)   # in this way we also convert to float64
train_data['EDUCATION'] = train_data['EDUCATION'].astype('float32')
test_data['EDUCATION'] = (test_data['EDUCATION'] - min_EDU) / (max_EDU - min_EDU)
test_data['EDUCATION'] = test_data['EDUCATION'].astype('float32')
display(train_data)
test_data

LIMIT_BAL  EDUCATION  MARRIAGE  AGE  ...  PAY_AMT5  PAY_AMT6  MALE  FEMALE
0       0.010101   0.333333         1   24  ...       0.0       0.0   0.0     1.0
1       0.111111   0.333333         2   26  ...       0.0    2000.0   0.0     1.0
2       0.080808   0.333333         2   34  ...    1000.0    5000.0   0.0     1.0
3       0.040404   0.333333         1   37  ...    1069.0    1000.0   0.0     1.0
4       0.040404   0.333333         1   57  ...     689.0     679.0   1.0     0.0
...          ...        ...       ...  ...  ...       ...       ...   ...     ...
26995   0.070707   0.333333         2   34  ...       0.0    4000.0   1.0     0.0
26996   0.212121   0.500000         1   39  ...    5000.0    1000.0   1.0     0.0
26997   0.141414   0.500000         2   43  ...       0.0       0.0   1.0     0.0
26998   0.020202   0.333333         2   37  ...    2000.0    3100.0   1.0     0.0
26999   0.070707   0.500000         1   41  ...   52964.0    1804.0   1.0     0.0

[27000 rows x 24 columns]

LIMIT_BAL  EDUCATION  MARRIAGE  AGE  ...  PAY_AMT5  PAY_AMT6  MALE  FEMALE
0      0.020202   0.500000         1   44  ...     379.0       0.0   0.0     1.0
1      0.252525   0.166667         2   28  ...   20074.0   60308.0   0.0     1.0
2      0.070707   0.166667         2   25  ...    3000.0    5000.0   1.0     0.0
3      0.060606   0.333333         2   42  ...    1841.0    1945.0   0.0     1.0
4      0.393939   0.500000         1   33  ...    4114.0    1855.0   1.0     0.0
...         ...        ...       ...  ...  ...       ...       ...   ...     ...
2995   0.202020   0.166667         2   28  ...    1572.0       0.0   1.0     0.0
2996   0.353535   0.166667         1   36  ...    8843.0    3000.0   0.0     1.0
2997   0.101010   0.333333         2   31  ...       0.0   93665.0   0.0     1.0
2998   0.333333   0.166667         2   44  ...    2434.0    2222.0   0.0     1.0
2999   0.282828   0.166667         1   40  ...     550.0       0.0   0.0     1.0

[3000 rows x 24 columns]

In [0]:
# MARRIAGE
train_marriage = keras.utils.to_categorical(train_data['MARRIAGE'])
marriage_columns = ['MARRIAGE_ONE', 'MARRIAGE_TWO', 'MARRIAGE_THREE', 'MARRIAGE_FOUR',]
train_marriage = pd.DataFrame(train_marriage, columns = marriage_columns)
train_data = pd.concat((train_data, train_marriage), axis = 'columns')
train_data.drop('MARRIAGE', axis = 'columns', inplace = True)
display(train_data)

test_marriage = keras.utils.to_categorical(test_data['MARRIAGE'])
test_marriage = pd.DataFrame(test_marriage, columns = marriage_columns)
test_data = pd.concat((test_data, test_marriage), axis = 'columns')
test_data.drop('MARRIAGE', axis = 'columns', inplace = True)
display(test_data)
del train_marriage, test_marriage, marriage_columns

LIMIT_BAL  EDUCATION  AGE  ...  MARRIAGE_TWO  MARRIAGE_THREE  MARRIAGE_FOUR
0       0.010101   0.333333   24  ...           1.0             0.0            0.0
1       0.111111   0.333333   26  ...           0.0             1.0            0.0
2       0.080808   0.333333   34  ...           0.0             1.0            0.0
3       0.040404   0.333333   37  ...           1.0             0.0            0.0
4       0.040404   0.333333   57  ...           1.0             0.0            0.0
...          ...        ...  ...  ...           ...             ...            ...
26995   0.070707   0.333333   34  ...           0.0             1.0            0.0
26996   0.212121   0.500000   39  ...           1.0             0.0            0.0
26997   0.141414   0.500000   43  ...           0.0             1.0            0.0
26998   0.020202   0.333333   37  ...           0.0             1.0            0.0
26999   0.070707   0.500000   41  ...           1.0             0.0            0.0

[27000 rows x 27 columns]

LIMIT_BAL  EDUCATION  AGE  ...  MARRIAGE_TWO  MARRIAGE_THREE  MARRIAGE_FOUR
0      0.020202   0.500000   44  ...           1.0             0.0            0.0
1      0.252525   0.166667   28  ...           0.0             1.0            0.0
2      0.070707   0.166667   25  ...           0.0             1.0            0.0
3      0.060606   0.333333   42  ...           0.0             1.0            0.0
4      0.393939   0.500000   33  ...           1.0             0.0            0.0
...         ...        ...  ...  ...           ...             ...            ...
2995   0.202020   0.166667   28  ...           0.0             1.0            0.0
2996   0.353535   0.166667   36  ...           1.0             0.0            0.0
2997   0.101010   0.333333   31  ...           0.0             1.0            0.0
2998   0.333333   0.166667   44  ...           0.0             1.0            0.0
2999   0.282828   0.166667   40  ...           1.0             0.0            0.0

[3000 rows x 27 columns]

In [0]:
# AGE
min_AGE = 21.
max_AGE = max(train_data['AGE'].max(), test_data['AGE'].max())
train_data['AGE'] = (train_data['AGE'] - min_AGE) / (max_AGE - min_AGE)
test_data['AGE'] = (test_data['AGE'] - min_AGE) / (max_AGE - min_AGE)
display(train_data)
test_data

LIMIT_BAL  EDUCATION  ...  MARRIAGE_THREE  MARRIAGE_FOUR
0       0.010101   0.333333  ...             0.0            0.0
1       0.111111   0.333333  ...             1.0            0.0
2       0.080808   0.333333  ...             1.0            0.0
3       0.040404   0.333333  ...             0.0            0.0
4       0.040404   0.333333  ...             0.0            0.0
...          ...        ...  ...             ...            ...
26995   0.070707   0.333333  ...             1.0            0.0
26996   0.212121   0.500000  ...             0.0            0.0
26997   0.141414   0.500000  ...             1.0            0.0
26998   0.020202   0.333333  ...             1.0            0.0
26999   0.070707   0.500000  ...             0.0            0.0

[27000 rows x 27 columns]

LIMIT_BAL  EDUCATION  ...  MARRIAGE_THREE  MARRIAGE_FOUR
0      0.020202   0.500000  ...             0.0            0.0
1      0.252525   0.166667  ...             1.0            0.0
2      0.070707   0.166667  ...             1.0            0.0
3      0.060606   0.333333  ...             1.0            0.0
4      0.393939   0.500000  ...             0.0            0.0
...         ...        ...  ...             ...            ...
2995   0.202020   0.166667  ...             1.0            0.0
2996   0.353535   0.166667  ...             0.0            0.0
2997   0.101010   0.333333  ...             1.0            0.0
2998   0.333333   0.166667  ...             1.0            0.0
2999   0.282828   0.166667  ...             0.0            0.0

[3000 rows x 27 columns]

In [0]:
print(np.sort(train_data['PAY_0'].unique()))
print(np.sort(train_data['PAY_2'].unique()))
print(np.sort(train_data['PAY_3'].unique()))
print(np.sort(train_data['PAY_4'].unique()))
print(np.sort(train_data['PAY_5'].unique()))
print(np.sort(train_data['PAY_6'].unique()))

[-2 -1  0  1  2  3  4  5  6  7  8]
[-2 -1  0  1  2  3  4  5  6  7  8]
[-2 -1  0  1  2  3  4  5  6  7  8]
[-2 -1  0  1  2  3  4  5  6  7  8]
[-2 -1  0  2  3  4  5  6  7  8]
[-2 -1  0  2  3  4  5  6  7  8]


We can see that all the `PAY` columns have identiacal structure, so that they can be normalized in the same way.

In [0]:
min_PAY = -2
max_PAY = 8
def scale(x, min, max):
  return (x - min) / (max - min)
train_data.loc[:, 'PAY_0':'PAY_6'] = scale(train_data.loc[:, 'PAY_0':'PAY_6'], min_PAY, max_PAY)
display(train_data)
test_data.loc[:, 'PAY_0':'PAY_6'] = scale(test_data.loc[:, 'PAY_0':'PAY_6'], min_PAY, max_PAY)
display(test_data)

LIMIT_BAL  EDUCATION  ...  MARRIAGE_THREE  MARRIAGE_FOUR
0       0.010101   0.333333  ...             0.0            0.0
1       0.111111   0.333333  ...             1.0            0.0
2       0.080808   0.333333  ...             1.0            0.0
3       0.040404   0.333333  ...             0.0            0.0
4       0.040404   0.333333  ...             0.0            0.0
...          ...        ...  ...             ...            ...
26995   0.070707   0.333333  ...             1.0            0.0
26996   0.212121   0.500000  ...             0.0            0.0
26997   0.141414   0.500000  ...             1.0            0.0
26998   0.020202   0.333333  ...             1.0            0.0
26999   0.070707   0.500000  ...             0.0            0.0

[27000 rows x 27 columns]

LIMIT_BAL  EDUCATION  ...  MARRIAGE_THREE  MARRIAGE_FOUR
0      0.020202   0.500000  ...             0.0            0.0
1      0.252525   0.166667  ...             1.0            0.0
2      0.070707   0.166667  ...             1.0            0.0
3      0.060606   0.333333  ...             1.0            0.0
4      0.393939   0.500000  ...             0.0            0.0
...         ...        ...  ...             ...            ...
2995   0.202020   0.166667  ...             1.0            0.0
2996   0.353535   0.166667  ...             0.0            0.0
2997   0.101010   0.333333  ...             1.0            0.0
2998   0.333333   0.166667  ...             1.0            0.0
2999   0.282828   0.166667  ...             0.0            0.0

[3000 rows x 27 columns]

In [0]:
print(np.sort(train_data['BILL_AMT1'].unique()))
print(np.sort(train_data['BILL_AMT2'].unique()))
print(np.sort(train_data['BILL_AMT3'].unique()))
print(np.sort(train_data['BILL_AMT4'].unique()))
print(np.sort(train_data['BILL_AMT5'].unique()))
print(np.sort(train_data['BILL_AMT6'].unique()))

[-165580. -154973.  -15308. ...  630458.  653062.  964511.]
[-69777. -67526. -33350. ... 671563. 743970. 983931.]
[-157264.  -61506.  -46127. ...  693131.  855086. 1664089.]
[-170000.  -81334.  -65167. ...  628699.  706864.  891586.]
[-81334. -61372. -53007. ... 587067. 823540. 927171.]
[-339603. -209051. -150953. ...  527711.  699944.  961664.]


In [0]:
from sklearn.preprocessing import StandardScaler
train_data.loc[:, 'BILL_AMT1':'BILL_AMT6'] = StandardScaler().fit_transform(train_data.loc[:, 'BILL_AMT1':'BILL_AMT6'])
test_data.loc[:, 'BILL_AMT1':'BILL_AMT6'] = StandardScaler().fit_transform(test_data.loc[:, 'BILL_AMT1':'BILL_AMT6'])
display(train_data)
test_data

LIMIT_BAL  EDUCATION  ...  MARRIAGE_THREE  MARRIAGE_FOUR
0       0.010101   0.333333  ...             0.0            0.0
1       0.111111   0.333333  ...             1.0            0.0
2       0.080808   0.333333  ...             1.0            0.0
3       0.040404   0.333333  ...             0.0            0.0
4       0.040404   0.333333  ...             0.0            0.0
...          ...        ...  ...             ...            ...
26995   0.070707   0.333333  ...             1.0            0.0
26996   0.212121   0.500000  ...             0.0            0.0
26997   0.141414   0.500000  ...             1.0            0.0
26998   0.020202   0.333333  ...             1.0            0.0
26999   0.070707   0.500000  ...             0.0            0.0

[27000 rows x 27 columns]

LIMIT_BAL  EDUCATION  ...  MARRIAGE_THREE  MARRIAGE_FOUR
0      0.020202   0.500000  ...             0.0            0.0
1      0.252525   0.166667  ...             1.0            0.0
2      0.070707   0.166667  ...             1.0            0.0
3      0.060606   0.333333  ...             1.0            0.0
4      0.393939   0.500000  ...             0.0            0.0
...         ...        ...  ...             ...            ...
2995   0.202020   0.166667  ...             1.0            0.0
2996   0.353535   0.166667  ...             0.0            0.0
2997   0.101010   0.333333  ...             1.0            0.0
2998   0.333333   0.166667  ...             1.0            0.0
2999   0.282828   0.166667  ...             0.0            0.0

[3000 rows x 27 columns]

In [0]:
print(np.sort(train_data['PAY_AMT1'].unique()))
print(np.sort(train_data['PAY_AMT2'].unique()))
print(np.sort(train_data['PAY_AMT3'].unique()))
print(np.sort(train_data['PAY_AMT4'].unique()))
print(np.sort(train_data['PAY_AMT5'].unique()))
print(np.sort(train_data['PAY_AMT6'].unique()))
print(np.sort(test_data['PAY_AMT1'].unique()))
print(np.sort(test_data['PAY_AMT2'].unique()))
print(np.sort(test_data['PAY_AMT3'].unique()))
print(np.sort(test_data['PAY_AMT4'].unique()))
print(np.sort(test_data['PAY_AMT5'].unique()))
print(np.sort(test_data['PAY_AMT6'].unique()))

[0.00000e+00 1.00000e+00 2.00000e+00 ... 4.93358e+05 5.05000e+05
 8.73552e+05]
[0.000000e+00 1.000000e+00 2.000000e+00 ... 1.215471e+06 1.227082e+06
 1.684259e+06]
[0.00000e+00 1.00000e+00 2.00000e+00 ... 5.08229e+05 8.89043e+05
 8.96040e+05]
[0.00000e+00 1.00000e+00 2.00000e+00 ... 4.97000e+05 5.28897e+05
 6.21000e+05]
[0.00000e+00 1.00000e+00 2.00000e+00 ... 3.79267e+05 4.17990e+05
 4.26529e+05]
[0.00000e+00 1.00000e+00 2.00000e+00 ... 4.43001e+05 5.27143e+05
 5.28666e+05]
[0.00000e+00 1.00000e+00 3.00000e+00 ... 1.91446e+05 1.95316e+05
 2.35728e+05]
[0.00000e+00 1.00000e+00 2.00000e+00 ... 2.74526e+05 3.44261e+05
 4.15552e+05]
[0.00000e+00 1.00000e+00 2.00000e+00 ... 2.82562e+05 3.24097e+05
 3.38394e+05]
[0.00000e+00 1.00000e+00 2.00000e+00 ... 1.60000e+05 1.68342e+05
 1.77202e+05]
[0.00000e+00 1.00000e+00 2.00000e+00 ... 3.10135e+05 3.17077e+05
 3.88071e+05]
[0.00000e+00 1.00000e+00 2.00000e+00 ... 2.01277e+05 2.04395e+05
 2.20371e+05]


In [0]:
from sklearn.preprocessing import MinMaxScaler
train_data.loc[:, 'PAY_AMT1':'PAY_AMT6'] = MinMaxScaler().fit_transform(train_data.loc[:, 'PAY_AMT1':'PAY_AMT6'])
test_data.loc[:, 'PAY_AMT1':'PAY_AMT6'] = MinMaxScaler().fit_transform(test_data.loc[:, 'PAY_AMT1':'PAY_AMT6'])
display(train_data)
test_data

LIMIT_BAL  EDUCATION  ...  MARRIAGE_THREE  MARRIAGE_FOUR
0       0.010101   0.333333  ...             0.0            0.0
1       0.111111   0.333333  ...             1.0            0.0
2       0.080808   0.333333  ...             1.0            0.0
3       0.040404   0.333333  ...             0.0            0.0
4       0.040404   0.333333  ...             0.0            0.0
...          ...        ...  ...             ...            ...
26995   0.070707   0.333333  ...             1.0            0.0
26996   0.212121   0.500000  ...             0.0            0.0
26997   0.141414   0.500000  ...             1.0            0.0
26998   0.020202   0.333333  ...             1.0            0.0
26999   0.070707   0.500000  ...             0.0            0.0

[27000 rows x 27 columns]

LIMIT_BAL  EDUCATION  ...  MARRIAGE_THREE  MARRIAGE_FOUR
0      0.020202   0.500000  ...             0.0            0.0
1      0.252525   0.166667  ...             1.0            0.0
2      0.070707   0.166667  ...             1.0            0.0
3      0.060606   0.333333  ...             1.0            0.0
4      0.393939   0.500000  ...             0.0            0.0
...         ...        ...  ...             ...            ...
2995   0.202020   0.166667  ...             1.0            0.0
2996   0.353535   0.166667  ...             0.0            0.0
2997   0.101010   0.333333  ...             1.0            0.0
2998   0.333333   0.166667  ...             1.0            0.0
2999   0.282828   0.166667  ...             0.0            0.0

[3000 rows x 27 columns]

In [0]:
train_targets_resh = keras.utils.to_categorical(train_targets)

<br><br/>
## Model Construction

This is a binary classification task, so we can make a model in which:
1. the output neuron is one, with an output value $\in [0,1]$, representing the Bayesian probability that the class is positive, i.e. the configdence of the NN on the fact that class = 1.
1. a good loss function is the categorical crossentropy
1. we can choose the sigmoid as an activation function for the output layer

Let us buil a model with ReLU hidden layers

In [0]:
def create_model():
  model = keras.models.Sequential()
  model.add(keras.layers.Dense(27, input_shape = (27,), activation = 'relu'))
  model.add(keras.layers.Dense(27, activation = 'relu'))
  model.add(keras.layers.Dense(27, activation = 'relu'))
  model.add(keras.layers.Dense(1, activation = 'sigmoid'))
  model.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])
  return model

What are the right metrics for this task? Are rare classes present?

In [0]:
index, value = np.unique(train_targets, return_counts = True)
index = np.array(index, dtype = 'str')
value = 100 * value / np.sum(value) # from abs frequ to % rel freq
class_count = pd.Series(value, index = index)
display(class_count)

0    77.877778
1    22.122222
dtype: float64

So the baseline for accuracy is ~78%. The two classes are unbalanced, but not heavily so. Still, it is wise to compute precision and recal other than the accuracy.

In [0]:
def get_conf_mat(model, data, targets):
  predictions = model.predict(data)
  predictions = predictions.reshape((predictions.size,))
  predictions = predictions > 0.5
  targets = np.array(targets, dtype = 'bool')
  TP = np.sum( (predictions == 1) & (targets == 1) )
  TN = np.sum( (predictions == 0) & (targets == 0) )
  FP = np.sum( (predictions == 1) & (targets == 0) )
  FN = np.sum( (predictions == 0) & (targets == 1) )
  row_index = pd.Index(['0', '1'], name = 'Predicted class')
  columns_index = pd.Index(['0', '1'], name = 'Actual class')
  matrix = [[TN, FN],
            [FP, TP]]
  return pd.DataFrame(matrix, index = row_index, columns = columns_index)
def get_metrics(model, data, targets):
  conf_matrix = get_conf_mat(model, data, targets)
  precision = conf_matrix.loc['1', '1'] / ( conf_matrix.loc['1', '1'] + conf_matrix.loc['1', '0'])
  recall = conf_matrix.loc['1', '1'] / ( conf_matrix.loc['1', '1'] + conf_matrix.loc['0', '1'])
  f_measure = precision * recall / (precision + recall)
  metrics = pd.Series([precision, recall, f_measure], index = ['precision', 'recall', 'F-measure'])
  return metrics

In [0]:
from sklearn.model_selection import StratifiedKFold
def cross_validate(mod_builder, data, targets, n_folds = 5, epochs = 10,
                   class_weights = None):
  '''
  Cross validates a model. CV is made with stratified sampling.
  '''
  splitter = StratifiedKFold(n_folds, shuffle = True)
  models = list()
  metrics_list = list()
  for train, test in splitter.split(data, targets):
    train_data = data.loc[train, :]
    train_targets = targets[train]
    model = mod_builder()
    models.append(model)
    model.fit(train_data, train_targets, batch_size = 128, epochs = epochs,
              class_weight = class_weights)
    
    test_data = data.loc[test, :]
    test_targets = targets[test]
    metrics_list.append(get_metrics(model, test_data, test_targets))
  
  return metrics_list

In [0]:
cross_validate(create_model, train_data, train_targets)

Epoch 1/10
21600/21600 [==============================] - 2s 97us/step - loss: 0.5948 - acc: 0.7404
Epoch 2/10
21600/21600 [==============================] - 0s 14us/step - loss: 0.5386 - acc: 0.7788
Epoch 3/10
21600/21600 [==============================] - 0s 16us/step - loss: 0.5319 - acc: 0.7788
Epoch 4/10
21600/21600 [==============================] - 0s 15us/step - loss: 0.5291 - acc: 0.7788
Epoch 5/10
21600/21600 [==============================] - 0s 15us/step - loss: 0.5270 - acc: 0.7788
Epoch 6/10
21600/21600 [==============================] - 0s 15us/step - loss: 0.5251 - acc: 0.7788
Epoch 7/10
21600/21600 [==============================] - 0s 16us/step - loss: 0.5232 - acc: 0.7788
Epoch 8/10
21600/21600 [==============================] - 0s 15us/step - loss: 0.5214 - acc: 0.7788
Epoch 9/10
21600/21600 [==============================] - 0s 15us/step - loss: 0.5196 - acc: 0.7788
Epoch 10/10
21600/21600 [==============================] - 0s 15us/step - loss: 0.5177 - acc: 0.7788

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in long_scalars


Epoch 1/10
21600/21600 [==============================] - 2s 100us/step - loss: 0.6045 - acc: 0.7128
Epoch 2/10
21600/21600 [==============================] - 0s 15us/step - loss: 0.5317 - acc: 0.7788
Epoch 3/10
21600/21600 [==============================] - 0s 14us/step - loss: 0.5264 - acc: 0.7788
Epoch 4/10
21600/21600 [==============================] - 0s 16us/step - loss: 0.5240 - acc: 0.7788
Epoch 5/10
21600/21600 [==============================] - 0s 15us/step - loss: 0.5218 - acc: 0.7788
Epoch 6/10
21600/21600 [==============================] - 0s 16us/step - loss: 0.5195 - acc: 0.7788
Epoch 7/10
21600/21600 [==============================] - 0s 16us/step - loss: 0.5170 - acc: 0.7788
Epoch 8/10
21600/21600 [==============================] - 0s 17us/step - loss: 0.5145 - acc: 0.7788
Epoch 9/10
21600/21600 [==============================] - 0s 16us/step - loss: 0.5120 - acc: 0.7788
Epoch 10/10
21600/21600 [==============================] - 0s 16us/step - loss: 0.5095 - acc: 0.778

[precision    NaN
 recall       0.0
 F-measure    NaN
 dtype: float64, precision    1.000000
 recall       0.000838
 F-measure    0.000837
 dtype: float64, precision    NaN
 recall       0.0
 F-measure    NaN
 dtype: float64, precision    NaN
 recall       0.0
 F-measure    NaN
 dtype: float64, precision    NaN
 recall       0.0
 F-measure    NaN
 dtype: float64]

### Let's Try Another Model

In [0]:
def build_2nd():
  mod = keras.models.Sequential()
  mod.add( keras.layers.Dense(27*27, activation = 'relu', input_shape = (27,)) )
  mod.add( keras.layers.Dense(27*27, activation = 'relu') )
  mod.add( keras.layers.Dense(27*27, activation = 'relu') )
  mod.add( keras.layers.Dense(27*27, activation = 'relu') )
  mod.add( keras.layers.Dense(27*27, activation = 'relu') )
  mod.add( keras.layers.Dense(27*27, activation = 'relu') )
  mod.add( keras.layers.Dense(27*27, activation = 'relu') )
  mod.add( keras.layers.Dense(1, activation = 'sigmoid'))
  mod.compile(optimizer = 'sgd', loss = 'binary_crossentropy', metrics = ['accuracy'])
  return mod

In [0]:
cross_validate(build_2nd, train_data, train_targets)

Epoch 1/10
21600/21600 [==============================] - 16s 755us/step - loss: 0.5957 - acc: 0.7707
Epoch 2/10
21600/21600 [==============================] - 13s 608us/step - loss: 0.5332 - acc: 0.7788
Epoch 3/10
21600/21600 [==============================] - 13s 613us/step - loss: 0.5291 - acc: 0.7788
Epoch 4/10
21600/21600 [==============================] - 13s 624us/step - loss: 0.5281 - acc: 0.7788
Epoch 5/10
21600/21600 [==============================] - 13s 610us/step - loss: 0.5273 - acc: 0.7788
Epoch 6/10
21600/21600 [==============================] - 13s 613us/step - loss: 0.5264 - acc: 0.7788
Epoch 7/10
21600/21600 [==============================] - 13s 605us/step - loss: 0.5256 - acc: 0.7788
Epoch 8/10
21600/21600 [==============================] - 13s 620us/step - loss: 0.5245 - acc: 0.7788
Epoch 9/10
21600/21600 [==============================] - 13s 619us/step - loss: 0.5232 - acc: 0.7788
Epoch 10/10
21600/21600 [==============================] - 13s 601us/step - loss: 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in long_scalars


Epoch 1/10
21600/21600 [==============================] - 16s 744us/step - loss: 0.5974 - acc: 0.7690
Epoch 2/10
21600/21600 [==============================] - 13s 619us/step - loss: 0.5329 - acc: 0.7788
Epoch 3/10
21600/21600 [==============================] - 13s 616us/step - loss: 0.5287 - acc: 0.7788
Epoch 4/10
21600/21600 [==============================] - 13s 609us/step - loss: 0.5276 - acc: 0.7788
Epoch 5/10
21600/21600 [==============================] - 13s 612us/step - loss: 0.5266 - acc: 0.7788
Epoch 6/10
21600/21600 [==============================] - 13s 612us/step - loss: 0.5256 - acc: 0.7788
Epoch 7/10
21600/21600 [==============================] - 13s 618us/step - loss: 0.5245 - acc: 0.7788
Epoch 8/10
21600/21600 [==============================] - 13s 611us/step - loss: 0.5231 - acc: 0.7788
Epoch 9/10
21600/21600 [==============================] - 13s 608us/step - loss: 0.5215 - acc: 0.7788
Epoch 10/10
21600/21600 [==============================] - 13s 604us/step - loss: 

[precision    NaN
 recall       0.0
 F-measure    NaN
 dtype: float64, precision    NaN
 recall       0.0
 F-measure    NaN
 dtype: float64, precision    NaN
 recall       0.0
 F-measure    NaN
 dtype: float64, precision    NaN
 recall       0.0
 F-measure    NaN
 dtype: float64, precision    NaN
 recall       0.0
 F-measure    NaN
 dtype: float64]

## Forse ci siamo!

In [0]:
cross_validate(create_model, train_data, train_targets, class_weights= {0: 0.23, 1: 0.77})

Epoch 1/10
21600/21600 [==============================] - 0s 23us/step - loss: 0.2455 - acc: 0.3088
Epoch 2/10
21600/21600 [==============================] - 0s 11us/step - loss: 0.2422 - acc: 0.3615
Epoch 3/10
21600/21600 [==============================] - 0s 11us/step - loss: 0.2413 - acc: 0.4042
Epoch 4/10
21600/21600 [==============================] - 0s 11us/step - loss: 0.2409 - acc: 0.4991
Epoch 5/10
21600/21600 [==============================] - 0s 11us/step - loss: 0.2407 - acc: 0.5505
Epoch 6/10
21600/21600 [==============================] - 0s 11us/step - loss: 0.2405 - acc: 0.5537
Epoch 7/10
21600/21600 [==============================] - 0s 11us/step - loss: 0.2403 - acc: 0.5868
Epoch 8/10
21600/21600 [==============================] - 0s 13us/step - loss: 0.2401 - acc: 0.6057
Epoch 9/10
21600/21600 [==============================] - 0s 12us/step - loss: 0.2399 - acc: 0.5958
Epoch 10/10
21600/21600 [==============================] - 0s 13us/step - loss: 0.2398 - acc: 0.6008

[precision    0.296020
 recall       0.497908
 F-measure    0.185647
 dtype: float64, precision    0.264629
 recall       0.507113
 F-measure    0.173888
 dtype: float64, precision    0.278200
 recall       0.398326
 F-measure    0.163799
 dtype: float64, precision    0.251172
 recall       0.224456
 F-measure    0.118532
 dtype: float64, precision    0.307877
 recall       0.428811
 F-measure    0.179209
 dtype: float64]

In [0]:
cross_validate(create_model, train_data, train_targets, class_weights= {0: 0.10, 1: 0.90})






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/10





21600/21600 [==============================] - 10s 469us/step - loss: 0.1936 - acc: 0.4211
Epoch 2/10
21600/21600 [==============================] - 1s 38us/step - loss: 0.1779 - acc: 0.2442
Epoch 3/10
21600/21600 [==============================] - 1s 37us/step - loss: 0.1712 - acc: 0.2225
Epoch 4/10
21600/21600 [==============================] - 1s 32us/step - loss: 0.1678 - acc: 0.2214
Epoch 5/10
21600/21600 [==============================] - 1s 32us/step - loss: 0.1661 - acc: 0.2213
Epoch 6/10
21600/21600 [==============================] - 1s 34us/step - loss: 0.1653 - acc: 0.2212
Epoch 7/10
21600/21600 [==============================] - 1s 33us/step - loss: 0.1648 - acc: 0.2212
Epoch 8/10
21600/21600 [==============================] - 1s 33us/step - loss: 0.1645 - acc: 0.2212
Epoch 9/10
21600/21600 [==============================] - 1s 33us/step - loss: 0.1643 - acc

[precision    0.221337
 recall       1.000000
 F-measure    0.181225
 dtype: float64, precision    0.221296
 recall       1.000000
 F-measure    0.181198
 dtype: float64, precision    0.221296
 recall       1.000000
 F-measure    0.181198
 dtype: float64, precision    0.221111
 recall       1.000000
 F-measure    0.181074
 dtype: float64, precision    0.221111
 recall       1.000000
 F-measure    0.181074
 dtype: float64]

In [0]:
cross_validate(create_model, train_data, train_targets, class_weights= {0: 0.15, 1: 0.85})

Epoch 1/10
21600/21600 [==============================] - 1s 51us/step - loss: 0.2039 - acc: 0.2724
Epoch 2/10
21600/21600 [==============================] - 1s 35us/step - loss: 0.2031 - acc: 0.2515
Epoch 3/10
21600/21600 [==============================] - 1s 36us/step - loss: 0.2027 - acc: 0.2393
Epoch 4/10
21600/21600 [==============================] - 1s 35us/step - loss: 0.2023 - acc: 0.2352
Epoch 5/10
21600/21600 [==============================] - 1s 32us/step - loss: 0.2019 - acc: 0.2346
Epoch 6/10
21600/21600 [==============================] - 1s 32us/step - loss: 0.2016 - acc: 0.2333
Epoch 7/10
21600/21600 [==============================] - 1s 36us/step - loss: 0.2013 - acc: 0.2341
Epoch 8/10
21600/21600 [==============================] - 1s 37us/step - loss: 0.2010 - acc: 0.2329
Epoch 9/10
21600/21600 [==============================] - 1s 33us/step - loss: 0.2007 - acc: 0.2327
Epoch 10/10
21600/21600 [==============================] - 1s 32us/step - loss: 0.2004 - acc: 0.2325

[precision    0.221826
 recall       0.988285
 F-measure    0.181163
 dtype: float64, precision    0.221336
 recall       0.998326
 F-measure    0.181169
 dtype: float64, precision    0.221296
 recall       1.000000
 F-measure    0.181198
 dtype: float64, precision    0.221152
 recall       1.000000
 F-measure    0.181101
 dtype: float64, precision    0.221152
 recall       1.000000
 F-measure    0.181101
 dtype: float64]

In [0]:
cross_validate(create_model, train_data, train_targets, class_weights= {0: 0.19, 1: 0.81})

Epoch 1/10
21600/21600 [==============================] - 1s 65us/step - loss: 0.2266 - acc: 0.2274
Epoch 2/10
21600/21600 [==============================] - 1s 35us/step - loss: 0.2260 - acc: 0.2249
Epoch 3/10
21600/21600 [==============================] - 1s 33us/step - loss: 0.2255 - acc: 0.2234
Epoch 4/10
21600/21600 [==============================] - 1s 34us/step - loss: 0.2251 - acc: 0.2229
Epoch 5/10
21600/21600 [==============================] - 1s 35us/step - loss: 0.2248 - acc: 0.2225
Epoch 6/10
21600/21600 [==============================] - 1s 33us/step - loss: 0.2245 - acc: 0.2226
Epoch 7/10
21600/21600 [==============================] - 1s 37us/step - loss: 0.2242 - acc: 0.2226
Epoch 8/10
21600/21600 [==============================] - 1s 37us/step - loss: 0.2240 - acc: 0.2225
Epoch 9/10
21600/21600 [==============================] - 1s 38us/step - loss: 0.2238 - acc: 0.2226
Epoch 10/10
21600/21600 [==============================] - 1s 38us/step - loss: 0.2236 - acc: 0.2229

[precision    0.221584
 recall       1.000000
 F-measure    0.181390
 dtype: float64, precision    0.224754
 recall       0.974059
 F-measure    0.182617
 dtype: float64, precision    0.221227
 recall       0.992469
 F-measure    0.180903
 dtype: float64, precision    0.232342
 recall       0.922948
 F-measure    0.185616
 dtype: float64, precision    0.223923
 recall       0.979899
 F-measure    0.182271
 dtype: float64]

In [0]:
cross_validate(build_2nd, train_data, train_targets, class_weights= {0: 0.23, 1: 0.77})

Epoch 1/10
21600/21600 [==============================] - 2s 82us/step - loss: 0.2423 - acc: 0.2598
Epoch 2/10
21600/21600 [==============================] - 1s 47us/step - loss: 0.2421 - acc: 0.6551
Epoch 3/10
21600/21600 [==============================] - 1s 42us/step - loss: 0.2420 - acc: 0.7381
Epoch 4/10
21600/21600 [==============================] - 1s 45us/step - loss: 0.2419 - acc: 0.7555
Epoch 5/10
21600/21600 [==============================] - 1s 44us/step - loss: 0.2418 - acc: 0.7636
Epoch 6/10
21600/21600 [==============================] - 1s 50us/step - loss: 0.2417 - acc: 0.7681
Epoch 7/10
21600/21600 [==============================] - 1s 44us/step - loss: 0.2416 - acc: 0.7712
Epoch 8/10
21600/21600 [==============================] - 1s 49us/step - loss: 0.2415 - acc: 0.7719
Epoch 9/10
21600/21600 [==============================] - 1s 49us/step - loss: 0.2414 - acc: 0.7730
Epoch 10/10
21600/21600 [==============================] - 1s 48us/step - loss: 0.2413 - acc: 0.7750

[precision    0.351648
 recall       0.026778
 F-measure    0.024883
 dtype: float64, precision    0.544118
 recall       0.061925
 F-measure    0.055597
 dtype: float64, precision    0.645161
 recall       0.066946
 F-measure    0.060652
 dtype: float64, precision    0.642857
 recall       0.045226
 F-measure    0.042254
 dtype: float64, precision    0.659091
 recall       0.048576
 F-measure    0.045242
 dtype: float64]

In [0]:
cross_validate(build_2nd, train_data, train_targets, class_weights= {0: 0.15, 1: 0.85})

NameError: ignored